=== jaalvarezGitHub/DAI/configuracion/configuracion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.esei.uvigo.es/dai/proyecto" 
	xmlns:tns="http://www.esei.uvigo.es/dai/proyecto"
	elementFormDefault="qualified">

<element name="configuration">
	<complexType>
		<sequence>
			<element name="connections">
				<complexType>
					<sequence>
						<element name="http" type="integer"/>
						<element name="webservice" type="string"/>
						<element name="numClients" type="byte"/> 	
					</sequence>
				</complexType>
			</element>
			
			<element name="database">
				<complexType>
					<sequence>
						<element name="user" type="string"/>
						<element name="password" type="string"/>
						<element name="url" type="string"/> 	
					</sequence>
				</complexType>
			</element>
			
			<element name="servers">
				<complexType>
					<sequence maxOccurs="unbounded">
						<element name="server" type="tns:server_type"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>

<complexType name="server_type">
	<attribute name="name" type="string"/>
	<attribute name="wsdl" type="string"/>
	<attribute name="namespace" type="string"/>
	<attribute name="service" type="string"/>
	<attribute name="httpAddress" type="string"/>
</complexType>


</schema>

=== jaalvarezGitHub/DAI/configuracion/configuracion_server1.xml
<?xml version="1.0" encoding="UTF-8"?>

<configuration
	xmlns="http://www.esei.uvigo.es/dai/proyecto"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.esei.uvigo.es/dai/proyecto configuracion.xsd"
>
	<connections>
		<http>10001</http>
		<webservice>http://localhost:20001/xmlserver</webservice>
		<numClients>50</numClients>
	</connections>
	<database>
		<user>user</user>
		<password>user</password>
		<url>jdbc:derby:C:\Users\usuario\Documents\GitHub\DAI\server1</url>
	</database>
	<servers>
		<server 
			name="Server 2" 
			wsdl="http://localhost:20002/xmlserver?wsdl"
			namespace="http://service.dai.esei.uvigo.es/"
			service="DaiServiceImplService"
			httpAddress="http://localhost:10002/"
		/>
		<server 
			name="Server 3" 
			wsdl="http://localhost:20003/xmlserver?wsdl"
			namespace="http://service.dai.esei.uvigo.es/"
			service="DaiServiceImplService"
			httpAddress="http://localhost:10003/"
		/>
	
	</servers>
</configuration>
